
    'p1_4_a_number':' " . showData('example') . "',	
    'p1_5_1':' " . showData('example') . "',	
    'p1_5_2':' " . showData('example') . "',	
    'p1_7_city_town':' " . showData('example') . "',	
    'p1_7_country':' " . showData('example') . "',	
    'p1_8_country_of_cityzen':' " . showData('example') . "',	
    'p1_9_uscis_online':' " . showData('example') . "',	
    'p1_10':' " . showData('example') . "',	
    'p1_10_a':' " . showData('example') . "',	
    'p1_10_b':' " . showData('example') . "',	
    'p1_10_c':' " . showData('example') . "',	
    'p1_10_d':' " . showData('example') . "',	
    'p1_10_e':' " . showData('example') . "',	
    'p1_10_f':' " . showData('example') . "',	
    'p1_10_g':' " . showData('example') . "',	
    'p1_10_h':' " . showData('example') . "',	
    'p1_11_a':' " . showData('example') . "',	
    'p1_11_b':' " . showData('example') . "',	
    'p1_11_c':' " . showData('example') . "',	
    